In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5,)
5
int64


In [ ]:
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr=np.zeros((3,3))
arr1=np.ones((3,3))
arr3=np.eye(3)
print(arr)
print(arr1)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
arr=np.linspace(0,1,10)

In [ ]:
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[11 22 33 44 55]
[ 9 18 27 36 45]
[10. 10. 10. 10. 10.]
[ 10  40  90 160 250]


In [ ]:
a=np.array([10,20,30,40,50])
print(a**2)
print(a**3)

[ 100  400  900 1600 2500]
[  1000   8000  27000  64000 125000]


In [ ]:
a=np.array([10,20,30,40,50])
print(a*1.15)

[11.5 23.  34.5 46.  57.5]


In [ ]:
a = np.array([10, 50, 30, 80])
b = np.array([20, 40, 60, 70])
print(np.maximum(a,b))
print(np.minimum(a,b))

[20 50 60 80]
[10 40 30 70]


In [ ]:
arr=np.arange(21)
print(arr)
print(arr[:5])
print(arr[-5:])
print(arr[5:16])
print(arr[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr=np.arange(10)
arr[:5]=100
print(arr[:8])
print(arr)

[100 100 100 100 100   5   6   7]
[100 100 100 100 100   5   6   7   8   9]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
view_arr=arr[1:4]
copy_arr=arr[1:4].copy()
view_arr[0]=999
copy_arr[1]=888
print(arr)
print(view_arr)
print(copy_arr)

[ 10 999  30  40  50]
[999  30  40]
[ 20 888  40]


In [ ]:
arr=np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1])
print(arr[:,2])
print(arr[1,1])

[40 50 60]
[30 60 90]
50


In [ ]:
arr1=arr[:2,1:]
print(arr1)

[[20 30]
 [50 60]]


In [ ]:
arr=np.arange(1,26).reshape(5,5)
print(arr[0])
print(arr[:,-1])
print(arr[2,2])
print(arr[:3,:3])

[1 2 3 4 5]
[ 5 10 15 20 25]
13
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr=np.arange(1,11).reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
arr = np.arange(30).reshape(5, 2, 3)
print(arr.transpose())

[[[ 0  6 12 18 24]
  [ 3  9 15 21 27]]

 [[ 1  7 13 19 25]
  [ 4 10 16 22 28]]

 [[ 2  8 14 20 26]
  [ 5 11 17 23 29]]]


In [ ]:
print(np.swapaxes(arr,0,2))

[[[ 0  6 12 18 24]
  [ 3  9 15 21 27]]

 [[ 1  7 13 19 25]
  [ 4 10 16 22 28]]

 [[ 2  8 14 20 26]
  [ 5 11 17 23 29]]]


In [ ]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr2=np.arange(11,20).reshape(3,3)
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
print(arr+arr2)
print(arr*arr2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [ ]:
print(np.dot(arr,arr2))

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [ ]:
transpose=arr.T
print(np.dot(transpose,arr))

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
